name: bitsdojo_window_windows
description: Windows implementation of the bitsdojo_window plugin.
version: 0.1.6
homepage: https://www.jasonholtdigital.com
repository: https://github.com/kingdomseed/desktop_title_bar_controls
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface:
    path: ../bitsdojo_window_platform_interface
  win32: ^5.1.1
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: BitsdojoWindowPlugin
