name: bitsdojo_window_platform_interface
description: A common platform interface for the bitsdojo_window plugin.
homepage: https://github.com/kingdomseed/desktop_title_bar_controls
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.1.2
repository: https://github.com/kingdomseed/desktop_title_bar_controls
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  flutter_lints: ^6.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.22.0"
